Feature/get markets api call
hyperxtend/MarketOverview pull request #1
Opened 2020-10-15 14:00 UTC by hyperxtend

2020-10-16 05:52 UTC, strange-developer requested changes

2020-10-16 05:52 UTC, strange-developer commented on src/components/coin-names/component.jsx
> +class CoinNames extends Component {
No need to use class components

2020-10-16 05:52 UTC, strange-developer commented on src/components/coin-names/component.jsx
> +		getAPIData(API_URLS.coinList, storageKeys.coinNames);
Isolate the API call so that getting the coin list data is as easy as calling a function.

2020-10-16 05:52 UTC, strange-developer commented on src/services/api/index.js
> +    .then((request) => request)
What does this line do?

2020-10-16 05:52 UTC, strange-developer commented on src/services/api/index.js
> +  try {
This try block will be better encompassing the entire code of this method since an API request also occurs here

2020-10-16 05:52 UTC, strange-developer commented on src/services/api/index.test.js
> +        { id: '01coin', symbol: 'zoc', name: '01coin' },
Change this data to have something like `test-coin`

2020-10-16 05:52 UTC, strange-developer commented on src/utils/index.js
> +export const getFirst20Items = items => {
Can limiting the result set rather be included as a parameter to the get coins API call? It can include a default setting as well so that the number of items do not need to be passed through all the time.

2020-10-16 06:50 UTC, strange-developer requested changes

2020-10-16 06:50 UTC, strange-developer commented on src/utils/index.js
> +};
I think do some research around whether this can be done better

2020-10-16 11:19 UTC, hyperxtend commented on src/services/api/index.js
> +    .then((request) => request)
It makes a call to the API to get the data from the API, using **.then()** returns a Promise & that Promise would return the data from the API depending on if that Promise is resolved or is rejected

2020-10-19 06:59 UTC, strange-developer requested changes

2020-10-19 06:59 UTC, strange-developer commented on src/components/coin-names/component.jsx
> +    const fetchDataFromAPI = async () => {
I think this is a good point to try using the `react-async` package.

2020-10-23 10:45 UTC, merged